--EN

exec ajouteOeuvre(1003012,'Harry Potter and the Deathly Hallows','''Give me Harry Potter,'' said Voldemort''s voice, and none shall be harmed. Give me Harry Potter, and I shall leave the school untouched. Give me Harry Potter, and you will be rewarded. As he climbs into the sidecar of Hagrid''s motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy...','Book',7,20,2,TO_DATE('1-1-2017', 'dd/mm/yyyy'),'Gallimard','J.K. Rowling',TO_DATE('1-1-2017', 'dd/mm/yyyy'),'Author');
exec ajouteOeuvre(2000340,'Flowers for Algernon', 'Charlie Gordon, a floor sweeper born with an unusually low IQ, has been chosen as the perfect subject for an experimental surgery that doctors hope will increase his intelligence - a procedure that has been highly successful when tested on a lab mouse named Algernon.All Charlie wants is to be smart and have friends, but the treatment turns him into a genius.Then Algernon begins to fade.What will become of Charlie?', 'Book', 100, 30, 5, TO_DATE('1-1-2002', 'dd/mm/yyyy'), 'Jai lu', 'Keyes, Daniel', TO_DATE('1-1-2002', 'dd/mm/yyyy'), 'Author');
exec ajouteOeuvre(23013,'Harry Potter and the Deathly Hallows','''Give me Harry Potter,'' said Voldemort''s voice, and none shall be harmed. Give me Harry Potter, and I shall leave the school untouched. Give me Harry Potter, and you will be rewarded. As he climbs into the sidecar of Hagrid''s motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy...','Book',2,25, 2,TO_DATE('01/01/2017','dd/mm/yyyy'),'Gallimard jeunesse','J.K. Rowling',TO_DATE('01/01/2017','dd/mm/yyyy'),'Author');
exec ajouteOeuvre(983489,'Asterix in Britain','One little ancient British village still holds out against the Roman invaders. Asterix and Obelix are invited to help. They must face fog, rain, warm beer and boiled boar with mint sauce, but they soon have Governor Encyclopaedicus Britannicus''s Romans declining and falling. Until a wild race for a barrel of magic potion lands them in the drink. It''s not quite cricket - how about a nice cup of hot water, though? Or even the first ever tea-party?','DVD',12,10,2,TO_DATE('1-1-2010', 'dd/mm/yyyy'),'not-specified','Yannik Piel',TO_DATE('1-1-2010', 'dd/mm/yyyy'),'Producer');
exec ajouteOeuvre(10299,'Fantastic Beasts and Where to Find Them','Fantastic Beasts and Where to Find Them opens in 1926 as Newt Scamander has just completed a global excursion to find and document an extraordinary array of magical creatures. Arriving in New York for a brief stopover, he might have come and gone without incident… were it not for a No-Maj (American for Muggle) named Jacob, a misplaced magical case, and the escape of some of Newt''s fantastic beasts, which could spell trouble for both the wizarding and No-Maj worlds','DVD',3,10,2,TO_DATE('01/01/2017','dd/mm/yyyy'),'not-specified','David Heyman',TO_DATE('01/01/2017','dd/mm/yyyy'),'Producer');
exec ajouteOeuvre(129876,'A Bug''s Life','A colony of blue ants, led by an aging Queen and her daughter Princess Atta, lives in the middle of a seasonally dry creekbed on a small hill known as "Ant Island". Every summer, they are forced to give food to a colony of grasshopper marauders, led by Hopper. One day, individualist and inventor Flik accidentally knocks....','DVD',2,10,2,TO_DATE('1-1-2001', 'dd/mm/yyyy'),'Disney - Pixar','Kevin Reher',TO_DATE('1-1-2001', 'dd/mm/yyyy'),'Producer');
exec ajouteOeuvre(654980,'Ice Age: The Meltdown','Manny, Sid, and Diego are currently living in a large valley surrounded by an enormously high ice wall on all sides. However, the trio discovers that the ice wall is actually a dam that is barely holding a massive body of water that could flood the valley to nearly a mile underwater. A vulture tells them that there is a boat at the other end of the valley that may save them all, but they only have three days to reach it or die. Manny is also currently worrying that he may be the last mammoth left...','DVD',5,10,2,TO_DATE('1-1-2006', 'dd/mm/yyyy'),'S.l.: Twentieth century fox','Saldanha',TO_DATE('1-1-2006', 'dd/mm/yyyy'),'Producer');
exec ajouteOeuvre(458976,'Back to black','Rehab;You know I''m no good;Me and Mr Jones;Just friends; Back to black; Love is a losing game; Tears dry on their own; Wake up alone;Some unholy war;He can only hold her;Addicted','CD',1,10,3,TO_DATE('1-1-2006', 'dd/mm/yyyy'),'ECM Records','Amy Winehouse',TO_DATE('1-1-2006', 'dd/mm/yyyy'),'Composer');
exec ajouteOeuvre(458977,'Back to black','Rehab;You know I''m no good;Me and Mr Jones;Just friends; Back to black; Love is a losing game; Tears dry on their own; Wake up alone;Some unholy war;He can only hold her;Addicted','CD',2,10,3,TO_DATE('1-1-2006', 'dd/mm/yyyy'),'Universal Records','Amy Winehouse',TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Composer');
exec ajouteOeuvre(780965,'Steve Jobs','In 1984, the Apple Macintosh 128K''s voice demo fails less than an hour before its unveiling at Flint Center. Apple co-founder Steve Jobs demands engineer Andy Hertzfeld to fix it, threatening to publicly implicate him in the presentation''s credits if he does not. Hertzfeld finally suggests faking the demo using the prototype Macintosh 512K computer','DVD',2,20,4,TO_DATE('1-1-2015', 'dd/mm/yyyy'),'Paris : Universal pictures vidéo France SA','The Mark Gordon Company',TO_DATE('1-1-2015', 'dd/mm/yyyy'),'Producer');
exec ajouteOeuvre(9876556,'All you need is','contenu : Heartbreak hotel;Tutti frutti;Shake,rattle and roll;That ''s all right;( Now and then there''s) ;A fool such as I;Marie ''s the name) His latest flame;I ''m left, you ''re right, she''s gone;The girl of my best friend;I got stung;Money honey;Such a night;Love me;Suspicion;Wear my ring around your neck;I love you because;Good luck charm;His hand in mine;Treat me nice;(Let me be your) Teddy bear;It''s now or never','CD', 1,10,2,TO_DATE('1-1-1956', 'dd/mm/yyyy'),'Third Face','Presley, Elvis',TO_DATE('1-1-2015', 'dd/mm/yyyy'),('Composer'));
exec ajouteOeuvre(343536,'Macbeth','Macbeth is loyal and courageous, and is a friend of King Duncan’s. However, after a battle he encounters three witches who tell him that one day he will be King of Scotland.Soon his obsession to become king is reinforced by his wife’s cold-blooded ambition…','Book',2,25,4,TO_DATE('1-1-1606', 'dd/mm/yyyy'),'Black cat','William Shakespeare',TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Author');
exec ajouteOeuvre(343578,'Macbeth','Macbeth is loyal and courageous, and is a friend of KingDuncan’s. However, after a battle he encounters three witches who tell him that one day he will be King of Scotland.Soon his obsession to becomeking is reinforced by his wife’s cold-blooded ambition…','CD',2,25,4,TO_DATE('1-1-1606', 'dd/mm/yyyy'),'Black cat','William Shakespeare',TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Author');
exec ajouteOeuvre(1213887,'Introduction to Differential Calculus','Enables readers to apply the fundamentals of differential calculus to solve real-life problems in engineering and the physical sciences Introduction to Differential Calculus fully engages readers by presenting the fundamental theories and methods of differential calculus and then showcasing how the discussed concepts can be applied to real-world problems in engineering and the physical sciences.','Book',6,30,3,TO_DATE('11-01-2012', 'dd/mm/yyyy'),'Wiley','Ulrich L. Rohde',TO_DATE('11-01-2012', 'dd/mm/yyyy'),'Author');
exec ajouteOeuvre(1213887,'Fishing For Dummies','From trout to carp, catfish to bonefish, freshwater to saltwater, the easy-to-follow pictures and tips help you recognize and deal with what you’ll meet in the murky deep. You’ll also find out about the best times and the right spots to cast your line, as well as the right gear—which in these hi-tech days includes GPS, apps, and sonar!...','Book',2,14,3,TO_DATE('01-09-2020', 'dd/mm/yyyy'),'For Dummies','Greg Schwipps',TO_DATE('01-09-2020', 'dd/mm/yyyy'),'Author');
















--FR
exec ajouteOeuvre(1000340,'Des fleurs pour Algernon', 'Algernon est une souris de laboratoire dont le traitement du Pr Nemur et du Dr Strauss vient de décupler l''intelligence. Enhardis par cette réussite, les deux savants tentent alors d''appliquer leur découverte à Charlie Gordon, un simple d''esprit. C''est bientôt l''extraordinaire éveil de l''intelligence pour le jeune homme. Il découvre un monde dont il avait toujours été exclu. Mais un jour, les facultés supérieures d''Algernon déclinent...', 'Livre', 100, 30, 5, TO_DATE('1-1-2002', 'dd/mm/yyyy'), 'Jai lu', 'Keyes, Daniel', TO_DATE('1-1-2002', 'dd/mm/yyyy'), 'Auteur');
exec ajouteOeuvre(203012,'Harry Potter et les reliques de la mort','Dans ce septième et dernier volet, Harry est confronté à une tâche dangereuse et apparemment impossible. Accompagné de Ron et Hermione, il part à la quête des Horcruxes restants de Voldemort afin de l anéantir. Il ne peut compter que sur sa force et doit suivre sans hésitation le sentier inexorable tracé pour lui par Dumbledore avant sa mort','Livre',7,20,2,TO_DATE('1-1-2017', 'dd/mm/yyyy'),'Gallimard','J.K. Rowling',TO_DATE('1-1-2017', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(203013,'Harry Potter et les reliques de la mort','Dans ce septième et dernier volet, Harry est confronté à une tâche dangereuse et apparemment impossible. Accompagné de Ron et Hermione,il part à la quête des Horcruxes restants de Voldemort afin de l anéantir.Il ne peut compter que sur sa force et doit suivre sans hésitation le sentier inexorable tracé pour lui par Dumbledore avant sa mort','Livre',2,25, 2,TO_DATE('01/01/2017','dd/mm/yyyy'),'Gallimard jeunesse','J.K. Rowling',TO_DATE('01/01/2017','dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(983489,'Astérix chez les bretons','Les romaines légions ont odieusement envahi l''Angleterre. Un petit village résiste encore et toujours.L''un de ses habitants, Jolitrax, contacte son cousin germain et gaulois, un certain Astérix.Celui-ci traverse la Manche en compagnie d''Obélix et Idéfix.','DVD',12,10,2,TO_DATE('1-1-2010', 'dd/mm/yyyy'),'non-renseigné','Yannik Piel',TO_DATE('1-1-2010', 'dd/mm/yyyy'),'Producteur');
exec ajouteOeuvre(10299,'Les animaux fantastiques','1926. Newt Scamander rentre à peine d''un périple à travers le monde où il a répertorié un bestiaire extraordinaire de créatures fantastiques.Il pense faire une courte halte à New York mais une série d''événements et de rencontres inattendues risquentde prolonger son séjour.C''est désormais le monde de la magie qui est menacé.','DVD',3,10,2,TO_DATE('01/01/2017','dd/mm/yyyy'),'non-renseigné','David Heyman',TO_DATE('01/01/2017','dd/mm/yyyy'),'Producteur');
exec ajouteOeuvre(129876,'1001 pattes','Oppressée par des sauterelles racketteuses, la fourmilière de la princesse Atta ne peut plus faire face.Tilt, inventeur insatiable mais maladroit légendaire,décide d''aller chercher du secours. En guise d''aide,il ne trouve qu''une troupe de cirque qu''il prend pour des héros...','DVD',2,10,2,TO_DATE('1-1-2001', 'dd/mm/yyyy'),'Disney - Pixar','Kevin Reher',TO_DATE('1-1-2001', 'dd/mm/yyyy'),'Producteur');
exec ajouteOeuvre(654980,'L''âge de glace 2','L''age de glace 2 : Pour Manny le mammouth, Sid le paresseux et Diego le tigre, la vie est beaucoup plus douce depuis que les glaces fondent et que la température remonte.Mais les problèmes ne sont pas terminés pour autant !Manny rêve de fonder une famille, mais la toute dernière femelle de son espèce, Ellie, se prend pour un opossum... Plus grave encore, un immense barrage de glace qui retient l''océan est sur le point de se rompre sous l''effet du réchauffement...','DVD',5,10,2,TO_DATE('1-1-2006', 'dd/mm/yyyy'),'S.l.: Twentieth century fox','Saldanha',TO_DATE('1-1-2006', 'dd/mm/yyyy'),'Producteur');
exec ajouteOeuvre(458976,'Back to black','Rehab;You know I''m no good;Me and Mr Jones;Just friends; Back to black; Love is a losing game; Tears dry on their own; Wake up alone;Some unholy war;He can only hold her;Addicted','CD',1,10,3,TO_DATE('1-1-2006', 'dd/mm/yyyy'),'ECM Records','Amy Winehouse',TO_DATE('1-1-2006', 'dd/mm/yyyy'),'Compositeur');
exec ajouteOeuvre(458977,'Back to black','Rehab;You know I''m no good;Me and Mr Jones;Just friends; Back to black; Love is a losing game; Tears dry on their own; Wake up alone;Some unholy war;He can only hold her;Addicted','CD',2,10,3,TO_DATE('1-1-2006', 'dd/mm/yyyy'),'Universal Records','Amy Winehouse',TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Compositeur');
exec ajouteOeuvre(780965,'Steve Jobs','Dans les coulisses, quelques instants avant le lancement de trois produits emblématiques ayant ponctué la carrière de Steve Jobs,du Macintosh en 1984 à l''iMac en 1998, le film nous entraîne dans les rouages de la révolution numérique pour dresser un portrait intime de l''homme de génie qui y a tenu une place centrale.','DVD',2,20,4,TO_DATE('1-1-2016', 'dd/mm/yyyy'),'Paris : Universal pictures vidéo France SA','Michael Fassbender',TO_DATE('1-1-2016', 'dd/mm/yyyy'),'Producteur');
exec ajouteOeuvre(9876556,'All you need is','contenu : Heartbreak hotel;Tutti frutti;Shake,rattle and roll;That ''s all right;( Now and then there''s) ;A fool such as I;Marie ''s the name) His latest flame;I ''m left, you ''re right, she''s gone;The girl of my best friend;I got stung;Money honey;Such a night;Love me;Suspicion;Wear my ring around your neck;I love you because;Good luck charm;His hand in mine;Treat me nice;(Let me be your) Teddy bear;It''s now or never','CD', 1,10,2,TO_DATE('1-1-1956', 'dd/mm/yyyy'),'Third Face','Presley, Elvis',TO_DATE('1-1-2015', 'dd/mm/yyyy'),('Compositeur'));
exec ajouteOeuvre(343536,'Macbeth','Macbeth is loyal and courageous, and is a friend of King Duncan’s. However, after a battle he encounters three witches who tell him that one day he will be King of Scotland.Soon his obsession to become king is reinforced by his wife’s cold-blooded ambition…','Livre',2,25,4,TO_DATE('1-1-1606', 'dd/mm/yyyy'),'Black cat','William Shakespeare',TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(343578,'Macbeth','Macbeth is loyal and courageous, and is a friend of KingDuncan’s. However, after a battle he encounters three witches who tell him that one day he will be King of Scotland.Soon his obsession to becomeking is reinforced by his wife’s cold-blooded ambition…','CD',2,25,4,TO_DATE('1-1-1606', 'dd/mm/yyyy'),'Black cat','William Shakespeare',TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(1213887,'Mathématiques','Première partie, Algèbre et géométrie.Deuxième partie, Analyse.Troisième partie, Arithmétique Probabilité.','Livre',6,30,3,TO_DATE('1-1-2020', 'dd/mm/yyyy'),'Louvain-la-Neuve : De Boeck supérieur','Pierre Burg',TO_DATE('1-1-2020', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(987766,'Réussir son potager et son verger','Un ouvrage pratique indispensable pour créer et entretenir un potager et un verger. Cet ouvrage vous montrera les techniques simples et pratiques pour obtenir des légumes savoureux. A chaque variété, sa saison, son terrain et sa technique de culture.Tout au long de ces pages vous découvrirez des légumes oubliéset vous pourrez ainsi déguster votre propre production.','Livre',2,40,2,TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Hachette collections','Christiane Hilaire',TO_DATE('1-1-2007', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(1298,'Les recettes de Noël les + faciles du monde','Des recettes lues en un coup d''oeil, réalisées en un tour de main !2 à 6 ingrédients par recette, présentés visuellement.Temps de préparation réduit.Une recette très courte, simple, claire et précise.Une belle photo du plat, explicite et gourmande.','Livre',2,40,2,TO_DATE('1-1-2020', 'dd/mm/yyyy'),'Vanves : Hachette cuisine','Jean-François Mallet',TO_DATE('1-1-2020', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(12568,'J''apprends à lire avec sami et julie - cp - niveau 2 - le carnaval de sami et julie','À l''école, c''est jour de fête  ! Pour le carnaval,tout le monde s''est déguisé... même les parents  !«J''apprends à lire avec Sami et Julie» est une collection de petites histoires spécialement conçue pour les enfants apprenant à lire','Livre',2,20,2,TO_DATE('1-1-2019', 'dd/mm/yyyy'),'Hachette "éducation','Thérèse Bonté',TO_DATE('1-1-2020', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(12987,'J''apprends à lire avec sami et julie - ce1 - vive les vacances !','Vive les vacances  ! Vive l''insousciance  ! Mais, patience, patience... Il faut d''abord finir les bagages et affronter quelques embouteillages...','Livre',6,20,2,TO_DATE('1-1-2018', 'dd/mm/yyyy'),'Hachette éducation','Thérèse Bonté',TO_DATE('1-1-2018', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(066667,'Printemps','Au printemps, les fleurs s''ouvrent et les insectes sortent. Un pop-up qui illustre cette saison.','Livre',12,15,2,TO_DATE('1-1-2016', 'dd/mm/yyyy'),'Gallimard','David A. Carter',TO_DATE('1-1-2016', 'dd/mm/yyyy'),'Auteur');
exec ajouteOeuvre(30662,'Printemps','Trois petites souris s''émerveillent de l''arrivée du printemps : les bourgeons des arbres, l''éclosion des fleurs, les gazouillis des oiseaux et le clapotis de la pluie.','Livre',12,15,2,TO_DATE('1-1-2020', 'dd/mm/yyyy'),'L''Ecole des loisirs','David A. Carter',TO_DATE('1-1-2020', 'dd/mm/yyyy'),'Auteur');
